config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :bookings, except: :index
  get 'refresh_calendar', to: 'bookings#refresh_calendar'
  resources :chatrooms, only: [ :show ] do
    collection do
      get 'find_or_create', to: 'chatrooms#find_or_create'
    end
    resources :messages, only: :create
  end

  resources :coordinates, only: %i(update)
end

app/models/booking.rb
class Booking < ApplicationRecord
  geocoded_by :address

  has_one :slot, dependent: :destroy
  has_one :teacher, through: :slot, as: :teacher
  belongs_to :student, class_name: 'User', foreign_key: 'student_id'
  has_many :coordinates, dependent: :destroy
  has_many :flashcards, through: :coordinates

  accepts_nested_attributes_for :slot

  validates  :student, presence: true

  after_validation :geocode, if: :will_save_change_to_address?

  def respect
    axis_rating("respect_rating")
  end

  def control
    axis_rating("control_rating")
  end

  def share
    axis_rating("share_rating")
  end

  def respect_color
    color(respect)
  end

  def control_color
    color(control)
  end

  def share_color
    color(share)
  end

private
  def axis_rating(rating_class)
    self[rating_class].nil? ? axis_rating = 0 : axis_rating = (self[rating_class]*(Math::PI / 5))
  end

  def color(angle)
    if angle < (Math::PI / 3)
      color = "#FD1015"
    elsif angle > (Math::PI / 3) && angle < ((Math::PI / 3)*2)
      color = "#ECA400"
    else
      color = "#139E10"
    end
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i(show edit update destroy)

  def index
    @bookings = policy_scope(Booking)
    authorize @bookings
  end

  def show
    authorize @booking
    @coordinates = @booking.coordinates
    booking_coordinates = @booking.coordinates.sort_by { |coordinate| coordinate.order}
    @coordinate_array = []
    booking_coordinates.each do |coordinate|
      @coordinate_array << [coordinate.longitude, coordinate.latitude]
    end

    @markers = []
    booking_coordinates.each do |coordinate|
      if coordinate.incident_category != 'no_display'
        @markers <<
        {
          coordinate_id: coordinate.id,
          incident_category: coordinate.incident_category,
          lng: coordinate.longitude,
          lat: coordinate.latitude
        }

      end
    end

    # @booking.geocode
    # @marker = {
    #     lat: @booking.latitude,
    #     lng: @booking.longitude
    # }
  end

  def new
    @booking = Booking.new
    @booking.build_slot
    authorize @booking
    @booking.geocode
    @marker = {
        lat: @booking.latitude,
        lng: @booking.longitude
    }

    @booking_id = nil
    # @booking.address = nil

    # for planning display
    @teachers = User.teachers.sort_by { |teacher| teacher.id }
    @teacher = @teachers.first
    generate_slots(DateTime.now().beginning_of_day)
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @student = current_user
    @booking.student = @student
    @booking.address = '16 villa Gaudelet 75011 Paris' if @booking.address == ""
    if @booking.save
      sleep 1
      redirect_to dashboard_path
    else
      redirect_to new_booking_path
      # @teachers = User.teachers.sort_by { |teacher| teacher.id }
      # @teacher = @teachers.first
      # generate_slots(DateTime.now().beginning_of_day)
      # render :new
    end
  end

  def edit
    authorize @booking
    @marker = {
      lat: @booking.latitude,
      lng: @booking.longitude
    }
    @teachers = User.teachers.sort_by { |teacher| teacher.id }
    @teacher = @booking.slot.teacher
    @slot = @booking.slot
    @booking_id = @booking.id
    generate_slots(@slot.start.beginning_of_day)
  end

  def update
    @booking.update(booking_params)
    @booking.slot.end = @booking.slot.start + 2.hours
    authorize @booking
    if @booking.save
      sleep 1
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def refresh_calendar
    @teacher = User.find(params[:teacher_id])
    if params[:refresh] == "next"
      generate_slots(params[:date].to_datetime + 4)
    elsif params[:refresh] == "previous"
      if (params[:date].to_datetime - 4) < DateTime.now().beginning_of_day
        generate_slots(DateTime.now().beginning_of_day)
      else
        generate_slots(params[:date].to_datetime - 4)
      end
    else
      generate_slots(params[:date].to_datetime)
    end

    if params[:booking_id]
      @booking_id = params[:booking_id]
      @slot = Booking.find(params[:booking_id]).slot
    end
    render partial: "slot_calendar"
    skip_authorization
  end

  def destroy
    @booking.destroy
    authorize @booking
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:address, :student_id, slot_attributes: [:id, :start, :teacher_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def generate_slots(start_date)
    @booked_slots = @teacher.slots.order(:start).where('start >= ?', DateTime.now().beginning_of_day)

    @final_slots = []
    starting_date = start_date
    day = DateTime.new(starting_date.year, starting_date.month, starting_date.day)
    5.times do
        time = 8
        6.times do
          start_time = DateTime.new(day.year, day.month, day.day, time)
          end_time = start_time + 2.hours
          @final_slots << Slot.new(teacher: @teacher, start: start_time, end: end_time)
          time = time + 2
        end
      day += 1
    end

    @booked_slots.each do |slot|
      final = @final_slots.find { |f| f.start == slot.start}
      final.booked = true if final
    end

    @hash = @final_slots.group_by { |slot| slot.start.day }
  end

end

app/views/bookings/_evaluationmap.html.erb
<div id="map"
     style="
     height: 500px;"
     data-coordinates="<%= @coordinate_array.to_json %>"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/bookings/_flashcard.html.erb
    <% coordinates.each do |coordinate| %>
      <div class='mt-3 flashcard-card js-flashcard-hidden' id='flashcard<%= coordinate.id %>'>
        <div>
          <strong><i class="fas fa-question-circle" style='font-size: 30px; color: #ECA53E'></i>  <%= coordinate.flashcard.question.capitalize %></strong>
        </div>
        <% if coordinate.student_answer.present? %>
          <div style='font-size: 18px; background-color: #EDF3F5; padding: 10px; color: #264060; margin-top: 10px'>
            <p><i><%= coordinate.student_answer %></i></p>
            <i class="fas fa-angle-double-right" style='font-size: 20px; color: #ECA53E'></i> <%= coordinate.flashcard.answer %>
          </div>
        <% else %>
          <div>
            <%= simple_form_for coordinate, remote: true do |f| %>
              <p></p>
              <%= f.input :student_answer, label: false, placeholder: 'Entre ta réponse ici...' %>
              <%= f.button :submit, class: 'btn btn-flashcard', value: 'Afficher la réponse' %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

app/views/bookings/_form.html.erb
<div class='content-evaluation'>

  <h2 id="teacher-bar-title">Choisis ton moniteur</h2>

  <div class='teacher-bar mt-3 mb-5'>
    <% teachers.each do |teacher| %>
      <div
        class='flex-column text-center column-teacher <%= @teacher.id == teacher.id ? 'teacher-selected' : 'teacher-free' %> js-initteacher'
        data-user-id=<%=teacher.id  %>
        data-path=<%= refresh_calendar_path(:teacher_id => teacher.id, :date => @hash.first[1].first.start.to_date, :refresh => nil, :booking_id => @booking_id) %>>
        <div class='border-avatar'>
          <%= cl_image_tag(teacher.photo.key, options = {class: 'avatar-large'}) if teacher.photo.attached? %>
        </div>
        <p><%= teacher.first_name %></p>
      </div>
    <% end %>
  </div>

  <h2 id="teacher-bar-title">Sélectionne un créneau</h2>
  <div id="container-calendar">
    <%= render partial: "slot_calendar" %>
  </div>

  <!-- <div class="my-2 js-next-btn hidden">
    <button class="border-0 btn-cardetour btn">SUIVANT</button>
  </div> -->

  <div class="js-location-selection">
    <%= simple_form_for(booking) do |f| %>

      <div>
          <div>
            <%= f.simple_fields_for :slot do |p| %>
              <%= p.hidden_field :teacher_id, value: teacher.id, input_html: { class: '', required: true }%>
              <%= p.hidden_field :start, input_html: { class: '', required: true } %>
            <% end %>
          </div>
          <h2 class="mt-4 mb-4">Sélectionne un lieu de rencontre</h2>
          <div>
            <div>
              <p class='mt-3' ><strong>La prise en charge se fait à l’auto-école par défaut.</strong>
              Si tu souhaites être récupéré au lieu de ton choix par ton moniteur, entre l’adresse ci-dessous :</p>
            </div>
            <div class='mapbox-card'>
              <%= f.input :address, label: false, input_html: { class: "address-form"} %>
              <div id="map"
                   style="
                   height: 300px;"
                   data-marker="<%= @marker.to_json %>"
                   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
          </div>
      </div>

      <div class="text-center my-3 <%= params[:action] == 'new' ? 'js-btn-new' : 'js-btn-edit' %>">
        <%= f.button :submit, class: "btn-cardetour js-btn-submit", value: 'Confirmer' %>
      </div>

    <% end %>
  </div>

</div>

app/views/bookings/_slot_calendar.html.erb
<div class="position-relative">
  <div class="calendar-container" data-first-date=<%= @hash.first[1][0].start.to_date %>>
    <div class="calendar-column_arrow">
      <button data-path=<%= refresh_calendar_path(:teacher_id => @teacher.id, :date => @hash.first[1].first.start.to_date, :refresh => 'previous', :booking_id => @booking_id) %> class="border-0 calendar-btn calendar-arrow">
        <i class="fas fa-chevron-left"></i>
      </button>
    </div>

    <% @hash.each do |day, value| %>
      <div class='calendar-column'>
        <div class='calendar-headers'>
          <div class="text-lowercase font-weight-bold"><%= I18n.l(value.first.start.to_datetime, format: :planning_month, locale: :fr) %></div>
          <div><%= I18n.l(value.first.start.to_datetime, format: :planning_day, locale: :fr) %></div>
        </div>

        <% value.each do |slot| %>
          <% if slot.start < DateTime.now() + 2.hour %>
            <div class="card-slot-booked">-</div>
          <% else %>
            <% if (@slot && (@slot.start == slot.start)) %>
              <div class='card-slot-clicked' data-slot=<%= slot.start.to_date %>  data-slot-hour=<%= slot.start.strftime('%H') %>>
                <%= slot.start.hour %>:00
              </div>
            <% elsif slot.booked %>
                <div class="card-slot-booked">-</div>
            <% else %>
              <div class='card-slot-free' data-slot=<%= slot.start.to_date %>  data-slot-hour=<%= slot.start.strftime('%H') %>>
                <%= slot.start.hour %>:00
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class="calendar-column_arrow">
      <button data-path=<%= refresh_calendar_path(:teacher_id => @teacher.id, :date => @hash.first[1].first.start.to_date, :refresh => 'next', :booking_id => @booking_id) %> class="border-0 calendar-btn calendar-arrow">
        <i class="fas fa-chevron-right"></i>
      </button>
    </div>
  </div>

  <div class="separator"></div>
</div>

app/views/bookings/edit.html.erb
<h1>Modifier ma réservation</h1>
<%= render partial: "form", locals: {booking: @booking, teachers: @teachers, teacher: @teacher}, action: 'edit'  %>

app/views/bookings/index.html.erb
<h1>My bookings</h1>

app/views/bookings/new.html.erb
<h1>Réserver un nouveau cours</h1>
<%= render partial: "form", locals: {booking: @booking, teachers: @teachers, teacher: @teacher}, action: 'new' %>

app/views/bookings/show.html.erb
<h1 style="margin-left:15px">Mon évaluation du <%= I18n.l(@booking.slot.start, format: :date_evaluation, locale: :fr) %></h1>

<div class="content-evaluation">

  <div class="">
    <h2 class="mb-2 mt-2">Mon niveau</h2>

    <div class="heures pt-4">
      <!-- SECTION 1 -->
      <div class="d-flex align-items-center mb-3">
      <!-- JAUGE 1 -->
        <div class="d-flex flex-column col-3 px-0">
          <div class="jauge">
            <svg width="100" height="50" xmlns="http://www.w3.org/2000/svg">
              <path d="M 0 50 A 50 50, 0, 1, 1 100 50 Z" fill="lightgrey">
              </path>
               <path d="M 0 50 A 50 50, 0, 0, 1 <%= 50 - Math.cos(@booking.respect)*50%> <%= 50 - Math.sin(@booking.respect)*50%> L 50 50 Z" fill="#24418C">
              </path>
            </svg>
            <div class="curseur"style="background-image: url('<%= image_path 'curseur.png' %>'); transform: rotate(<%= ((@booking.respect / (Math::PI / 5)) * 36 - 90 ) %>deg)">
            </div>
          </div>
          <h3 class="jauge-title my-1">Appréhender la route</h3>
        </div>
        <!-- TEXT BOX 1 -->
        <div class="row-evaluation col-9 mt-0 pr-0">
          <div class="card-evaluation-content">
            <p><%= @booking.review_content %></p>
          </div>
        </div>

      </div>

      <!-- SECTION 2 -->
      <div class="d-flex align-items-center mb-3">
      <!-- JAUGE 2 -->
        <div class="d-flex flex-column col-3 px-0">
          <div class="jauge">
            <svg width="100" height="50" xmlns="http://www.w3.org/2000/svg">
              <path d="M 0 50 A 50 50, 0, 1, 1 100 50 Z" fill="lightgrey">
              </path>
               <path d="M 0 50 A 50 50, 0, 0, 1 <%= 50 - Math.cos(@booking.share)*50%> <%= 50 - Math.sin(@booking.share)*50%> L 50 50 Z" fill="#47A1BD">
              </path>
            </svg>
            <div class="curseur"style="background-image: url('<%= image_path 'curseur.png' %>'); transform: rotate(<%= ((@booking.share / (Math::PI / 5)) * 36 - 90 ) %>deg)">
            </div>
          </div>
          <h3 class="jauge-title my-1">Partager la route</h3>
        </div>
        <!-- TEXT BOX 2 -->
        <div class="row-evaluation col-9 mt-0 pr-0">
          <div class="card-evaluation-content">
            <p><%= @booking.review_evaluation%></p>
          </div>
        </div>
      </div>

      <!-- SECTION 3 -->
      <div class="d-flex align-items-center mb-3">
      <!-- JAUGE 3 -->
        <div class="d-flex flex-column col-3 px-0">
          <div class="jauge">
            <svg width="100" height="50" xmlns="http://www.w3.org/2000/svg">
              <path d="M 0 50 A 50 50, 0, 1, 1 100 50 Z" fill="lightgrey">
              </path>
              <path d="M 0 50 A 50 50, 0, 0, 1 <%= 50 - Math.cos(@booking.control)*50%> <%= 50 - Math.sin(@booking.control)*50%> L 50 50 Z" fill="#F86513">
              </path>
            </svg>
            <div class="curseur"style="background-image: url('<%= image_path 'curseur.png' %>'); transform: rotate(<%= ((@booking.control / (Math::PI / 5)) * 36 - 90 ) %>deg)">
            </div>
          </div>
          <h3 class="jauge-title my-1">Maitriser son véhicule</h3>
        </div>
      <!-- TEXT BOX 3 -->
        <div class="row-evaluation col-9 mt-0 pr-0">
          <div class="card-evaluation-content">
            <p><%= @booking.review_to_improve%></p>
          </div>
        </div>
      </div>

    </div>

  </div>



  <div class="row-evaluation flex-column">
    <h2 class="mt-0 mb-2">Mon parcours</h2>
    <div class="heures">
      <div class='evaluation-map' id='eval_map'>
        <%= render partial: "evaluationmap", locals: {booking: @booking}  %>
      </div>
      <div class="evaluationmap-flashcard">
        <% if @booking.coordinates.count > 0 %>
          <div class="flashcard">
            <%= render "flashcard", coordinates: @booking.coordinates  %>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  </div>
</div>