config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :bookings, except: :index
  get 'refresh_calendar', to: 'bookings#refresh_calendar'
  resources :chatrooms, only: [ :show ] do
    collection do
      get 'find_or_create', to: 'chatrooms#find_or_create'
    end
    resources :messages, only: :create
  end

  resources :coordinates, only: %i(update)
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar-home.html.erb
<div class="navbar-expand-sm navbar-light navbar-cardetour-home fixed-top">

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "pauline.jpg", class: "avatar dropdown-toggle mt-1", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Tableau de bord", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "btn btn-outline-warning" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class=" navbar-expand-sm navbar-light navbar-cardetour">
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav mr-5">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to new_booking_path, class: "btn btn-warning btn-cardetour", data: { turbolinks: false }  do %>
          <i class="fas fa-plus mr-2"></i>RÉSERVER UN COURS
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Déconnexion", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="row d-flex justify-content-center">
  <%= link_to dashboard_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
</div>

<% if !bookings.empty? %>
  <h2 class= "mt-5 mb-0">Mon dernier cours</h2>
  <div class="row card-cours">
  <% last_booking = bookings.joins(:slot).where("slots.start < ?", DateTime.now()).order("slots.start").last %>
    <div class="d-flex ">
      <div class="col-3 mt-2">
        <%= cl_image_tag last_booking.slot.teacher.photo.key, class: "avatar-large"%>
      </div>
      <div class="col-9 mt-3">
        <h3 class="card-title mb-1"> Mon évaluation avec <%= last_booking.slot.teacher.first_name%></h3>
        <p class="card-title"> <i class="fas fa-calendar-alt"></i> <%= I18n.l(last_booking.slot.start, format: :date, locale: :fr).capitalize %></p>
      </div>
    </div>
    <div class="card-body d-flex flex-column">
      <div class="d-flex my-1">
        <div class="note-sidebar color-respect">
          <%=last_booking.respect_rating%>/5
        </div>
        <h3 class="m-2 jauge-title align-self-center mb-0" style="font-size: 12px;">APPRÉHENDER LA ROUTE</h3>
      </div>
      <div class="d-flex my-1">
        <div class="note-sidebar color-share">
          <%=last_booking.share_rating%>/5
        </div>
        <h3 class="m-2 jauge-title align-self-center mb-0" style="font-size: 12px;">PARTAGER LA ROUTE</h3>
      </div>
      <div class="d-flex my-1">
        <div class="note-sidebar color-control">
          <%=last_booking.control_rating%>/5
        </div>
        <h3 class="m-2 jauge-title align-self-center mb-0" style="font-size: 12px;">MAITRISER SON VÉHICULE</h3>
      </div>
    </div>

    <div class = "text-center mb-2">
      <% if last_booking.review_evaluation.nil? %>
        <%= link_to '#', class: "btn-outline btn-card-cardetour", id:"btn-blue" do%>
          EN ATTENTE D'ÉVALUATION
        <% end %>
      <% else %>
        <%= link_to booking_path(last_booking), class: "btn-outline btn-card-cardetour" do%>
          VOIR MON ÉVALUATION
        <% end %>
      <% end %>
    </div>
  </div>


  <div class="d-flex justify-content-between align-item-center">
    <h2 class= "mb-0">Mes cours à venir</h2>
    <div class="d-flex justify-content-between text-align-center">
    <%= link_to '+', new_booking_path, class: "btn-plus", style: 'font-size: 18px' %>
    </div>
  </div>

  <div class="row card-cours-f">
    <div class="card-scroll-futur">
    <% bookings_sorted = bookings.sort_by { |booking| booking.slot.start } %>
    <% bookings_s = bookings_sorted %>
    <% bookings_s.each do |booking| %>
      <% if booking.slot.start > DateTime.now()%>
        <div class="card card-booking">
          <div class="card-body">
            <div class= "d-flex">
              <h3 class="card-title"> <i class="fas fa-calendar-alt"></i> <%= I18n.l(booking.slot.start, format: :date_short, locale: :fr).capitalize %> </h3>
              <h3 class="card-title ml-2"> <i class="fas fa-clock"></i> <%= booking.slot.start.strftime("%H:%M")%></h3>
            </div>
            <h3 class="card-title address"> <i class="fas fa-map-marker-alt"></i> <%=booking.address%></h3>
            <div class="mt-4">
              <a><%= link_to "MODIFIER", edit_booking_path(booking), class:"btn-outline btn-card-cardetour"%></a>
              <a><%= link_to "ANNULER", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class:"btn-outline btn-card-cardetour"%></a>
            </div>
          </div>
          <div class="card-avatar">
            <%= cl_image_tag booking.slot.teacher.photo.key, class: "avatar"%>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
<% end %>