config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :bookings, except: :index
  get 'refresh_calendar', to: 'bookings#refresh_calendar'
  resources :chatrooms, only: [ :show ] do
    collection do
      get 'find_or_create', to: 'chatrooms#find_or_create'
    end
    resources :messages, only: :create
  end

  resources :coordinates, only: %i(update)
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= favicon_link_tag("favicon.png") %>
    <!-- petit logo sur l'onglet en haut à gauche -->
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <% if params[:action] == "home" || devise_controller?%>
      <%=  render 'shared/navbar-home' %>
    <% end %>

    <%= render 'shared/flashes' %>

    <% if params[:action] == "home" || devise_controller? %>
      <div class="content-wrapper-home">
        <%= yield %>
      </div>

    <% else %>
      <div class="container-cardetour">
          <% unless params[:action] == 'home' || devise_controller? %>
            <!-- SIDEB BAR -->
            <div class="cardetour-sidebar">
              <%= render 'shared/sidebar', bookings: @bookings %>
            </div>
          <!-- CONTENT -->
          <div class="cardetour-content">
            <div class="row justify-content-end" id="cardetour-nav">
              <%= render 'shared/navbar'%>
            </div>

            <div class="row content">
              <%= yield %>
            </div>
          </div>

        </div>
        <!-- CHAT -->
        <div class="btn-chat">
          <%= image_tag "message.png", class: "dropdown-toggle", id: "messageDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.teacher? %>
              <%User.all.each do |user|%>
                <%=link_to find_or_create_chatrooms_path(interlocutor: user), class: "dropdown-item d-flex justify-content-between" do%>
                <p><%= user.first_name %></p>
                <%= cl_image_tag user.photo.key, class: "avatar-chatbox" if user.photo.attached? %>
                <% end %>
              <% end %>
            <% else %>
              <%User.teachers.each do |teacher|%>
                <%=link_to find_or_create_chatrooms_path(interlocutor: teacher), class: "dropdown-item d-flex justify-content-between" do%>
                <p><%= teacher.first_name %></p>
                <%= cl_image_tag teacher.photo.key, class: "avatar-chatbox" if teacher.photo.attached?%>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <!-- AVATAR -->
        <div class = "nav-item dropdown fixed-top btn-avatar">
          <%= image_tag "pauline.jpg", class: " avatar dropdown-toggle mt-1", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Tableau de bord", dashboard_path, class: "dropdown-item" %>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>

       <% end %>
    <% end %>
  </body>
</html>